// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqiqekkhjdqhtxgoysmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxaXFla2toamRxaHR4Z295c21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjM3NDYsImV4cCI6MjA2Nzg5OTc0Nn0.738vnP19wAMMG2ZM6Sdke5UQ4yz6bmlCJ_nfBj1iTmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});